Make a class the represents y = Ax + b <br>
Assume X exists in Rn <br>
Assume Y exists in Rm <br>
constructor takes n, m <br>
generate RANDOM A, b <br>
functionUpdate output takes x and returns Ax + b <br>
updateOutput should cache Ax + b in self.output <br>

In [131]:
import random
import numpy as np

class xForm:
    def __init__( self, n, m, A = np.zeros( 0 ), b = np.array( 0 ), output = np.array( 0 ) ):
        self.n = n; # num rows
        self.m = m; # num cols
        self.A = np.zeros( (n,m) ) # generate reference matrix
        for i in range( m ):
            for j in range( n ):
                self.A[j,i] = np.random.random_integers( 0, 10 )
        self.b = np.random.random_integers( 0, 10, n )
    
    # generate a 0's matrix for reference
    def outZ( self ):
        return np.zeros( (self.n,self.m) )
    
    # print matrix A
    def outA( self ):
        return self.A
    
    # print array b
    def outB( self ):
        return self.b
    
    # attempt Ax = b
    def update( self ):
        self.output = np.linalg.solve( self.A, self.b )
        return np.linalg.solve( self.A, self.b )
        

In [132]:
test = xForm( 5, 5 )
print test.outA( )
print
print test.outB( )
print
x = np.array
x = test.update( )
print x

[[  4.   3.   0.   6.   7.]
 [  8.   2.   7.   2.   5.]
 [  4.   4.   0.  10.   6.]
 [  5.   0.   6.   0.   3.]
 [  2.   7.  10.   2.   4.]]

[4 7 5 1 3]

[ 2.   2.  -1.  -0.5 -1. ]
