In [1]:
import numpy as np

def f1(x,y):
    vec_1 = np.asarray(x)
    vec_2 = np.asarray(y)
    return np.add(vec_1,vec_2)

# adds 2 arrays

f1( [1,1],[2,5] )

array([3, 6])

In [2]:
def f2(a,x):
    return np.multiply(a,x)

# multiplies an array by a scalar

f2( 6,[100,3] )

array([600,  18])

In [3]:
def f3(x):
    arr_1 = np.asarray(x)
    norm = 0.0
    norm = np.sum(arr_1 * arr_1)
    norm = np.sqrt(norm)
    
    return np.multiply( x, 1/norm )

# calcs the norm of each component

f3( [1,1] )

array([ 0.70710678,  0.70710678])

In [4]:
def f4(x):
    return np.linalg.norm(x)

# calcs the norm of the whole vector

f4( [4,4] )

5.6568542494923806

In [5]:
def f5(x):
    npa = np.asarray(x)
    sig = lambda x: (1.0 / ( 1.0 + np.exp(-x)))
    
    return sig(npa)

f5([5,4,3])

array([ 0.99330715,  0.98201379,  0.95257413])

In [6]:
def f6(m, nrows, ncols):
    for i in range(nrows):
        for j in range(ncols):
            if m[ncols * i + j] != m[ncols * j + i]:
                return False
    return True

def f6c(m, nrows, ncols):
    npa = np.array(m)
    npb = np.reshape(npa, (nrows, ncols))
    
    return (npb == npb.T).all()
    
print f6([1,2,2,1],2,2)
print
print f6c([2,4,4,2], 2, 2)


True

True


In [51]:
def f7(x,y):
    s = 0.0
    if len(x) != len(y):
        raise ValueError("lengths differ.")
    for i,v in enumerate(x):
        s += x[i] * y[i]
    return s

def f7c(x,y):
    npm = np.matrix(x)
    npm_2 = np.matrix(y)
    #s = np.sum(np.multiply(npm, npm_2)) #use np.dot
    s = np.dot(npm, npm_2.T)
    return s

print f7([1,2],[2,5])
f7c([1,2],[2,5])

12.0


matrix([[12]])

In [46]:
def f8(m, x, nrows, ncols):
    result = []
    if len(x) != ncols:
        raise ValueError("m and x have incompatible sizes.")
    for i, v in enumerate(x):
        result.append(f7(m[i * ncols : (i+1)*ncols], x))
    return result

def f8c(m,x,nrows,ncols):
    npm = np.matrix(m)
    npm = np.reshape(npm, (nrows,ncols))
    npv = np.asarray(x)
    
    return np.dot(npm, npv)

print f8([3,2,1,4,5,4,3,4,5],[2,4,2],3,3)
print
print f8c([3,2,1,4,5,4,3,4,5],[2,4,2],3,3)

[16.0, 36.0, 32.0]

[[16 36 32]]


In [47]:
import random
def f9(length):
    result = []
    if length <= 0:
        raise ValueError("Need a positive argument.")
    for i in range(length):
        result.append(random.gauss(0, 0.1))
    return result

def f9c(length):
    if length <= 0:
        raise ValueError("Need a positive argument.")
    else:
        result = np.asarray(np.random.normal(0,0.1,length))
    return result
print f9(5)
print
f9c(6)

[-0.13299607549670409, 0.14664210369407435, 0.08768015819059143, -0.16856898833585898, 0.0755695069531221]



array([-0.08729116,  0.02252197, -0.02058702,  0.01969302,  0.12880577,
        0.07451925])

In [48]:
def f10(x):
    if len(x) == 0:
        raise ValueError("need a nonempty x.")
    minval = x[0]
    for v in x:
        if v <= minval:
            minval = v
    return minval

def f10c(x):
    if len(x) == 0:
        raise ValueError("need a nonempty x.")
    npa = np.asarray(x)
    return np.amin(npa)

print f10([1,2,3,4,0,6,5,-1])
print
f10c([1,2,3,4,0,6,5,-1])
    

-1



-1

In [49]:
def f11(x):
    if len(x) == 0:
        raise ValueError("need nonempty x.")
    maxval = x[0]
    for v in x:
        if v >= maxval:
            maxval = v
    return maxval

def f11c(x):
    if len(x) == 0:
        raise ValueError("need nonempty x.")
    return np.max(x)

print f11([1,2,3,4,0,6,5,-1])
print
f11c([1,2,3,4,0,6,5,-1])

6



6