In [23]:
import numpy as np

def f1(x,y):
    vec_1 = np.asarray(x)
    vec_2 = np.asarray(y)
    return np.add(vec_1,vec_2)

# adds 2 arrays

f1( [1,1],[2,5] )

array([3, 6])

In [20]:
def f2(a,x):
    return np.multiply(a,x)

# multiplies an array by a scalar

f2( 6,[100,3] )

array([600,  18])

In [47]:
def f3(x):
    arr_1 = np.asarray(x)
    norm = 0.0
    norm = np.sum(arr_1 * arr_1)
    norm = np.sqrt(norm)
    
    return np.multiply( x, 1/norm )

# calcs the norm of each component

f3( [1,1] )

array([ 0.70710678,  0.70710678])

In [34]:
def f4(x):
    return np.linalg.norm(x)

# calcs the norm of the whole vector

f4( [4,4] )

5.6568542494923806

In [53]:
def f5(x):
    npa = np.asarray(x)
    sig = lambda x: (1.0 / ( 1.0 + np.exp(-x)))
    
    return sig(npa)

f5([5,4,3])

array([ 0.99330715,  0.98201379,  0.95257413])

In [153]:
def f6(m, nrows, ncols):
    for i in range(nrows):
        for j in range(ncols):
            print m[ncols * i + j]
            print m[ncols * j + i]
            print
            if m[ncols * i + j] != m[ncols * j + i]:
                return False
    return True

def f6c(m, nrows, ncols):
    npm = np.matrix(m)
    return 0

print f6([1,1,3,1],1,3)
print
#print f6c((5,2,9),3,1)


1
1

1
1

3


IndexError: list index out of range

In [167]:
def f7(x,y):
    s = 0.0
    if len(x) != len(y):
        raise ValueError("lengths differ.")
    for i,v in enumerate(x):
        s += x[i] * y[i]
    return s

def f7c(x,y):
    npm = np.matrix(x)
    npm_2 = np.matrix(y)
    s = np.sum(np.multiply(npm, npm_2))
    return s

print f7([1,2],[2,5])
f7c([1,2],[2,5])

12.0


12

In [169]:
def f8(m, x, nrows, ncols):
    result = []
    if len(x) != ncols:
        raise ValueError("m and x have incompatible sizes.")
    for i, v in enumerate(x):
        result.append(f7(m[i * ncols : (i+1)*ncols], x))
    return result

def f8c(m,x,nrows,ncols):
    return 0

print f8([3,2,1],[2][1][1],1,3)

IndexError: list index out of range

In [93]:
import random
def f9(length):
    result = []
    if length <= 0:
        raise ValueError("Need a positive argument.")
    for i in range(length):
        result.append(random.gauss(0, 0.1))
    return result

def f9c(length):
    if length <= 0:
        raise ValueError("Need a positive argument.")
    else:
        result = np.asarray(np.random.normal(0,0.1,length))
    return result
print f9(5)
print
f9c(6)

[0.026557021274295635, -0.07655775580135626, -0.049665133836569175, -0.015723382252908567, -0.02323450204974597]



array([ 0.00656201,  0.26596203, -0.14789259, -0.04994129,  0.05739307,
       -0.1230581 ])

In [94]:
def f10(x):
    if len(x) == 0:
        raise ValueError("need a nonempty x.")
    minval = x[0]
    for v in x:
        if v <= minval:
            minval = v
    return minval

def f10c(x):
    if len(x) == 0:
        raise ValueError("need a nonempty x.")
    npa = np.asarray(x)
    return np.amin(npa)

print f10([1,2,3,4,0,6,5,-1])
print
f10c([1,2,3,4,0,6,5,-1])
    

-1



-1

In [95]:
def f11(x):
    if len(x) == 0:
        raise ValueError("need nonempty x.")
    maxval = x[0]
    for v in x:
        if v >= maxval:
            maxval = v
    return maxval

def f11c(x):
    if len(x) == 0:
        raise ValueError("need nonempty x.")
    return np.max(x)

print f11([1,2,3,4,0,6,5,-1])
print
f11c([1,2,3,4,0,6,5,-1])

6



6